# Generated by Django 5.0.4 on 2024-04-19 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0001_initial'),
        ('rate', '0002_alter_rate_user_rate_unique_rate_per_hall_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall.hall'),
        ),
    ]
