# Generated by Django 5.0.4 on 2024-04-22 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hall', '0002_hallattachments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reservation_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=255, null=True)),
                ('hall_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_reservation', to='hall.hall')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reservation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
