# Generated by Django 5.0.4 on 2024-04-22 14:42

import django.core.validators
import django.db.models.deletion
import hall.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=hall.models.bug_attachment, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'mp4', 'mkv', 'gif', 'webm', 'pdf', 'doc', 'docx', 'ogg', 'avl', 'txt'])])),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_attachments', to='hall.hall')),
            ],
        ),
    ]
